# Header
menu:
  Home: /
  About: /about
#rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: left
widgets:
- category
- tag
- archive
# - short-about

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
- category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

subtitle: 生命不息 代码不止

